# Generated by Django 4.2.15 on 2024-08-13 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('image', models.ImageField(upload_to='comics/images')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comics.comic')),
            ],
        ),
    ]
