# Generated by Django 4.2.15 on 2024-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='text_elements',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
